amazonProperties:
  endpointUrl: https://upload-image-shoppingcart.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4YKHWLEWYCEBE4WX
  secretKey: 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
  bucketName: upload-image-shoppingcart
