amazonProperties:
  endpointUrl: https://upload-image-shoppingcart.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4YKHWLEWTC6JJLFR
  secretKey: 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
  bucketName: upload-image-shoppingcart
spring:
  main:
    web-application-type=none:

## google auth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 69682817150-uj1a5m4tue0gp6jrkbad21d25i3gh832.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - email
              - profile

