amazonProperties:
  endpointUrl: https://upload-image-shoppingcart.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4YKHWLEWTC6JJLFR
  secretKey: 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
  bucketName: upload-image-shoppingcart
spring:
  main:
    web-application-type=none:

## google auth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 69682817150-5goult898gf0halj5r4lag70cpla5v43.apps.googleusercontent.com
            client-secret: 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
