amazonProperties:
  endpointUrl: https://upload-image-shoppingcart.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4YKHWLEWQ2EG6NKS
  secretKey: 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
  bucketName: upload-image-shoppingcart
spring:
  main:
    web-application-type=none:

## google oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 69682817150-gsogi2c7kp2ctmd0m7lho189cr991kj3.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: https://shopping-cart-demo.herokuapp.com/oauth2/callback/google
            redirect-uri: http://localhost:8080/oauth2/callback/google

            scope:
              - email
              - profile