amazonProperties:
  endpointUrl: https://upload-image-shoppingcart.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIA4YKHWLEW2INP2T7J
  secretKey: 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
  bucketName: upload-image-shoppingcart
